import numpy as np
import pandas as pd
from normalization import Normalizer

class DataPreprocessor:
    """Class for preprocessing data for logistic regression.
    Attributes:
        split (float): Proportion of data to use for training.
        normalizer (Normalizer): Instance of Normalizer for data normalization.
        data (DataFrame): Loaded dataset from CSV file.
    Methods:
        preprocess(): Preprocesses the data by normalizing and splitting into training and testing sets.
        Returns:
            tuple: (X_train, y_train, X_test, y_test) - Preprocessed training and testing data.
    
    NB: 1. The preprocess method normalizes the 'value' column of the dataset and splits the data into training and testing sets based on the specified split ratio.
           The normalized features and corresponding labels are returned for both sets.
        2. The dataset used in this class is already generated and stored in a CSV file named "data.csv",
           which contains two columns: 'value' (the feature) and 'label' (the target variable).
           The same data can generated by running the data_generation.py script, which creates a similar synthetic dataset for testing purposes.
    """


    def __init__(self, split=0.8):
        self.split = split
        self.normalizer = Normalizer()

        # Import the dataset in data.csv
        self.data = pd.read_csv("./data.csv")
    
    def preprocess(self):

        self.X = self.data['value'].values.reshape(-1,1)
        self.y = self.data['label'].values

        split_index = int(self.split * len(self.X))

        X_train = self.X[:split_index]
        X_test = self.X[split_index:]

        self.X_train = self.normalizer.normalize(X_train)
        self.X_test = (X_test - self.normalizer.mu) / self.normalizer.std
        self.y_train = self.y[:split_index]
        self.y_test = self.y[split_index:]

        return self.X_train, self.y_train, self.X_test, self.y_test